=== Saikrishna-dev-oss/web-technologies-GCET/gcet_programs/Att_company.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Company">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Employee">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="FirstName" type="xs:string"/>
                            <xs:element name="LastName" type="xs:string"/>
                            <xs:element name="ContactNo" type="xs:string"/>
                            <xs:element name="Email" type="xs:string"/>
                            <xs:element name="Address">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="City" type="xs:string"/>
                                        <xs:element name="State" type="xs:string"/>
                                        <xs:element name="Zip" type="xs:int"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>

                        <!-- Attribute -->
                        <xs:attribute name="empId" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>

            <!-- Attribute -->
            <xs:attribute name="companyId" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Saikrishna-dev-oss/web-technologies-GCET/gcet_programs/company.xml
<?xml version="1.0" encoding="UTF-8"?>
<Company companyId="C101"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="Att_company.xsd">

    <Employee empId="E001">
        <FirstName>Tanmay</FirstName>
        <LastName>Patil</LastName>
        <ContactNo>1234567890</ContactNo>
        <Email>tanmaypatil@xyz.com</Email>
        <Address>
            <City>Bangalore</City>
            <State>Karnataka</State>
            <Zip>560212</Zip>
        </Address>
    </Employee>

</Company>
